### ISSUE TITLE
Make app.css cacheable

### ISSUE THREAD

**Issue by lgierth** [dansup/hub#16]
Currently it seems appends a dynamic timestamp: `GET http://hub.hyperboria.net/assets/prod/app.css?v=1425004391`

**Comment by dansup** [comment]
The hub website is not running the same code as the dev branch, the template (css) assets are [not](https://github.com/dansup/hub/blob/master/app/views/template.php#L11-14) appended with timestamps, and we do plan to cache static assets. If you are using Apache with the .htaccess provided, you [will](https://github.com/dansup/hub/blob/master/public/.htaccess#L821) cache CSS files for 1 year.

Lighttpd and nginx configurations will be available soon.
